[toolchain]
anchor-lang = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
caramelo_token = "A55nLv1rkmtFVhL9UYnfYf48Nx4TyAhduFk1JKXejQpy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keys/phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

